import React from 'react'

export function GameBoard(props) {
    const userName = props.userName;
    const [score, setScore] = React.useState(null)


    return (
        <section className="gameboard">
        <div className='gameData'>{userName}</div>
        <div className='gameData'>Score: {score}</div>
        <table>
          <tbody>
          <tr>
            <td>
              <button>
                MM
              </button>
            </td>
            <td>
              <button>
                MM
              </button>
            </td>
            <td>
              <button>
                MM
              </button>
            </td>
            <td>
              <button>
                MM
              </button>
            </td>
            <td>
              <button>
                MM
              </button>
            </td>
          </tr>
                    <tr>
            <td>
              <button>
                MM
              </button>
            </td>
            <td>
              <button>
                MM
              </button>
            </td>
            <td>
              <button>
                MM
              </button>
            </td>
            <td>
              <button>
                MM
              </button>
            </td>
            <td>
              <button>
                MM
              </button>
            </td>
          </tr>
                    <tr>
            <td>
              <button>
                MM
              </button>
            </td>
            <td>
              <button>
                MM
              </button>
            </td>
            <td>
              <button>
                MM
              </button>
            </td>
            <td>
              <button>
                MM
              </button>
            </td>
            <td>
              <button>
                MM
              </button>
            </td>
          </tr>
                    <tr>
            <td>
              <button>
                MM
              </button>
            </td>
            <td>
              <button>
                MM
              </button>
            </td>
            <td>
              <button>
                MM
              </button>
            </td>
            <td>
              <button>
                MM
              </button>
            </td>
            <td>
              <button>
                MM
              </button>
            </td>
          </tr>
                    <tr>
            <td>
              <button>
                MM
              </button>
            </td>
            <td>
              <button>
                MM
              </button>
            </td>
            <td>
              <button>
                MM
              </button>
            </td>
            <td>
              <button>
                MM
              </button>
            </td>
            <td>
              <button>
                MM
              </button>
            </td>
          </tr>
          </tbody>
        </table>
        <div>
        <button className="newGame">New Game</button>
        </div>
      </section>
    ); 
}