import React from 'react';
import './game.css'
import { Sidebar } from './sidebar';

export function Game() {
  return (
    <main id="main_game">
      <Sidebar/>
      <section className="gameboard">
        <table>
          <tbody>
          <tr>
            <td>
              <button>
                MM
              </button>
            </td>
            <td>
              <button>
                MM
              </button>
            </td>
            <td>
              <button>
                MM
              </button>
            </td>
            <td>
              <button>
                MM
              </button>
            </td>
            <td>
              <button>
                MM
              </button>
            </td>
          </tr>
                    <tr>
            <td>
              <button>
                MM
              </button>
            </td>
            <td>
              <button>
                MM
              </button>
            </td>
            <td>
              <button>
                MM
              </button>
            </td>
            <td>
              <button>
                MM
              </button>
            </td>
            <td>
              <button>
                MM
              </button>
            </td>
          </tr>
                    <tr>
            <td>
              <button>
                MM
              </button>
            </td>
            <td>
              <button>
                MM
              </button>
            </td>
            <td>
              <button>
                MM
              </button>
            </td>
            <td>
              <button>
                MM
              </button>
            </td>
            <td>
              <button>
                MM
              </button>
            </td>
          </tr>
                    <tr>
            <td>
              <button>
                MM
              </button>
            </td>
            <td>
              <button>
                MM
              </button>
            </td>
            <td>
              <button>
                MM
              </button>
            </td>
            <td>
              <button>
                MM
              </button>
            </td>
            <td>
              <button>
                MM
              </button>
            </td>
          </tr>
                    <tr>
            <td>
              <button>
                MM
              </button>
            </td>
            <td>
              <button>
                MM
              </button>
            </td>
            <td>
              <button>
                MM
              </button>
            </td>
            <td>
              <button>
                MM
              </button>
            </td>
            <td>
              <button>
                MM
              </button>
            </td>
          </tr>
          </tbody>
        </table>
        <div>
        <button className="newGame">New Game</button>
        </div>
      </section>
    </main>
  );
}